[package]
name = "ptarmigan"
version = "0.6.0"
authors = ["tgblackburn"]
edition = "2018"
publish = false
readme = "README.md"
license = "Apache-2.0"
build = "build.rs"

[dependencies]
mpi = {version = "0.5", optional = true}
rand = "0.7"
rand_xoshiro = "0.4"
rand_distr = "0.2"
meval = "0.2.0"
yaml-rust = "0.4.5"
num = "0.2"
fitsio = {version = "0.15", optional = true}
memoffset = {version = "0.5", optional = true}
hdf5 = {version = "0.7.0", optional = true}
unzip-n = {version = "0.1.2", optional = true}

[features]
default = []
fits-output = ["fitsio"]
hdf5-output = ["hdf5", "unzip-n"]
with-mpi = ["mpi", "memoffset"]
compensating-chirp = []
no-radiation-reaction = []
cos2-envelope-in-3d = []

[build-dependencies]
vergen = "4.0.3"
