[package]
name = "ptarmigan"
version = "0.1.0"
authors = ["tgblackburn"]
edition = "2018"
publish = false
readme = "README.md"
license = "Apache-2.0"

[dependencies]
mpi = "0.5"
rand = "0.7"
rand_xoshiro = "0.4"
rand_distr = "0.2"
meval = "0.2.0"
yaml-rust = "0.4"
num = "0.2"
fitsio = {version = "0.15", optional = true}

[features]
default = []
fits-output = ["fitsio"]
