name: build
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  no-hdf5-output:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose -- --test-threads=1